#! /bin/bash

createview() {
	local cbnode=$1
	local viewsrc=$2
	local bucket=$3
	local docname=$4
	local password=$5

	if [ $password ]; then
		useropt="--basic --user $bucket:$password"
	fi

	if [ ! -r $viewsrc ] ; then
		echo "Cannot read $viewsrc" >&2
		return 1
	fi
	curl $useropt -X PUT --data @${viewsrc} -H "Content-Type:application/json"\
	       "http://${cbnode}/${bucket}/_design/${docname}"
}

usage() {
	echo "Usage: momo-create-views [-b <bucket>] [-n <host>] [-s <view source dir>] [-p]" >&2
	exit 1
}

node='localhost:8092'
bucket='default'
srcdir='/usr/share/momo'

params=$(getopt -n momo-create-views -o b:n:s:puh -l bucket:,node:,src-dir:,password,usage,help -- "$@")
eval set -- "$params"

while true; do
	case "$1" in
	-b|--bucket) 
		bucket="$2"; shift 2
		;;
	-n|--node)
		node="$2"; shift 2
		;;
	-s|--src-dir)
		srcdir="$2"; shift 2
		;;
	-p|--password)
		use_password=true; shift 1
		;;
	-u|-h|--usage|--help)
		usage
		;;
	--)
		break;
	esac
done

if [ $use_password ]; then
	echo -n "Bucket Password: "
	read -s password
	echo
fi

for json in ${srcdir}/*.json; do
	docname=$(basename ${json%.json})
	createview $node $json $bucket $docname $password
done

